#!/bin/bash

pkg::dependency_check() {
  which make >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -yqq make
  fi

  which gcc >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -yqq gcc
  fi

  which g++ >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    if [ "$(os::is_centos)" = "true" ]; then
      pm install -yy gcc-c++
    elif [ "$(os::is_ubuntu)" = "true" ]; then
      pm install -yy g++
    fi
  fi

  # install version manager
  pkg::install_version_manager
}

pkg::config_profile() {
  zgvm env
}

pkg::install_version_manager() {
  which zgvm >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro plugin install gvm
  else
    zmicro plugin update gvm
  fi
}

pkg::install() {
  # Depdendency Check
  pkg::dependency_check

  # Install Binary
  zgvm install $version

  # Apply Profile
  pkg::config_profile

  # Install Packages
  pkg::install_packages
}

pkg::install_packages() {
  # Bin
  export PATH=$(zgvm bin):$PATH

  if [ "${#PACKAGE_DEFAULT_PACKAGES}" = "0" ]; then
    return
  fi

  log::info "Install Packages ..."

  install_one() {
    local name=${@:2}

    log::info "  [pacakges: $name] installing ..."
    # @TODO
    go install $name
    if [ "$?" != "0" ]; then
      log::error "  [pacakges: $name] install error"
      return
    fi

    log::success "  [pacakges: $name] install done"
  }

  # bash shell cannot export array as env
  #   stackoverflow: https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable
  config::load_file $PACKAGES_PATH/$PACKAGE_NAME/config

  which go >> /dev/null 2>&1
  if [ "$?" = "0" ]; then
    array::each install_one ${PACKAGE_DEFAULT_PACKAGES[@]} 
  fi
}

pkg::update() {
  pkg::install
}

export -f pkg::dependency_check

export -f pkg::config_profile

export -f pkg::install
export -f pkg::install_version_manager
export -f pkg::install_packages

export -f pkg::update

