#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package remove $PACKAGE_NAME"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  # remove link
  sudo rm /usr/local/node
  # remove libs
  sudo rm -rf $ZMICRO_PLUGINS_DATA_PATH/gvm
  # remove home lib
  sudo rm -rf $HOME/.node
}

run() {
  core $@
}

run $@
