#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package update go"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  pkg::update
}

run() {
  core $@
}

run $@
